export const GET_MOVIES = 'GET_MOVIES'
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS'
export const GET_MOVIES_FAIL = 'GET_MOVIES_FAIL'
export const ADD_MOVIES_SUCCESS = 'ADD_MOVIES_SUCCESS'
export const ADD_MOVIES = 'ADD_MOVIES'
export const ADD_MOVIES_FAIL = 'ADD_MOVIES_FAIL'

export const EDIT_MOVIES = 'EDIT_MOVIES'
export const EDIT_MOVIES_SUCCESS = 'EDIT_MOVIES_SUCCESS'
export const EDIT_MOVIES_FAIL = 'EDIT_MOVIES_FAIL'

export const DELETE_MOVIES = 'DELETE_MOVIES';
export const DELETE_MOVIES_SUCCESS = 'DELETE_MOVIES_SUCCESS';
export const DELETE_MOVIES_FAIL = 'DELETE_MOVIES_FAIL';
export const SEARCH_MOVIE = 'SEARCH_MOVIE'